- params:
    name: ShortestPath
    model: baseline # name of the model
    architecture_name: advanced
    N: 1000 # dataset size
    noise: 0.5 # noise halfwidth parameter
    deg: 6 # degree of misspecification
    scheduler: False # scheduler (boolean)
    max_epochs: 30 # maximum number of epochs
    min_epochs: 5 # minimum number of epochs
    num_workers: 0 # maximum number of workers
    batch_size: 128 # batch size
    normalization: "zscore" # norm
  smac:
    walltime_limit: 86400
    n_trials: 200
    config_space_name: baseline_mse_configspace
    seed: 0

- params:
    name: ShortestPath
    model: SPO # name of the model
    architecture_name: advanced
    N: 1000 # dataset size
    noise: 0.5 # noise halfwidth parameter
    deg: 6 # degree of misspecification
    scheduler: False # scheduler (boolean)
    max_epochs: 30 # maximum number of epochs
    min_epochs: 5 # minimum number of epochs
    num_workers: 0 # maximum number of workers
    batch_size: 128 # batch size
    normalization: "zscore" # norm
  smac:
    walltime_limit: 86400
    n_trials: 200
    config_space_name: spo_configspace
    seed: 0

# - params:
#     name: ShortestPath
#     model: DBB # name of the model
#     architecture_name: advanced
#     N: 1000 # dataset size
#     noise: 0.5 # noise halfwidth parameter
#     deg: 6 # degree of misspecification
#     scheduler: False # scheduler (boolean)
#     max_epochs: 30 # maximum number of epochs
#     min_epochs: 5 # minimum number of epochs
#     num_workers: 0 # maximum number of workers
#     batch_size: 128 # batch size
#     normalization: "zscore" # norm
#   smac:
#     walltime_limit: 86400
#     n_trials: 200
#     config_space_name: dbb_configspace
#     seed: 0

- params:
    name: ShortestPath
    model: CachingPO # name of the model
    loss: pairwise # loss
    architecture_name: advanced
    N: 1000 # dataset size
    noise: 0.5 # noise halfwidth parameter
    deg: 6 # degree of misspecification
    scheduler: False # scheduler (boolean)
    max_epochs: 30 # maximum number of epochs
    min_epochs: 5 # minimum number of epochs
    num_workers: 0 # maximum number of workers
    batch_size: 128 # batch size
    normalization: "zscore" # norm
    growth: 0.05 # growth parameter of rankwise losses
    num_samples: 1
  smac:
    walltime_limit: 86400
    n_trials: 200
    config_space_name: caching_pairwise_configspace
    seed: 0

- params:
    name: ShortestPath
    model: CachingPO # name of the model
    loss: pairwise_diff # loss
    architecture_name: advanced
    N: 1000 # dataset size
    noise: 0.5 # noise halfwidth parameter
    deg: 6 # degree of misspecification
    scheduler: False # scheduler (boolean)
    max_epochs: 30 # maximum number of epochs
    min_epochs: 5 # minimum number of epochs
    num_workers: 0 # maximum number of workers
    batch_size: 128 # batch size
    normalization: "zscore" # norm
    growth: 0.05 # growth parameter of rankwise losses
    num_samples: 1
  smac:
    walltime_limit: 86400
    n_trials: 200
    config_space_name: caching_pairwise_diff_configspace
    seed: 0

# - params:
#     name: ShortestPath
#     model: DCOL # name of the model
#     architecture_name: advanced
#     N: 1000 # dataset size
#     noise: 0.5 # noise halfwidth parameter
#     deg: 6 # degree of misspecification
#     scheduler: False # scheduler (boolean)
#     max_epochs: 30 # maximum number of epochs
#     min_epochs: 5 # minimum number of epochs
#     num_workers: 0 # maximum number of workers
#     batch_size: 128 # batch size
#     normalization: "zscore" # norm
#   smac:
#     walltime_limit: 86400
#     n_trials: 200
#     config_space_name: dcol_configspace 
#     seed: 0

# - params:
#     name: ShortestPath
#     model: FenchelYoung # name of the model
#     architecture_name: advanced
#     N: 1000 # dataset size
#     noise: 0.5 # noise halfwidth parameter
#     deg: 6 # degree of misspecification
#     scheduler: False # scheduler (boolean)
#     max_epochs: 30 # maximum number of epochs
#     min_epochs: 5 # minimum number of epochs
#     num_workers: 0 # maximum number of workers
#     batch_size: 128 # batch size
#     normalization: "zscore" # norm
#     num_samples: 1
#   smac:
#     walltime_limit: 86400
#     n_trials: 200
#     config_space_name: fenchel_young_configspace 
#     seed: 0


# - params:
#     name: ShortestPath
#     model: IntOpt # name of the model
#     architecture_name: advanced
#     N: 1000 # dataset size
#     noise: 0.5 # noise halfwidth parameter
#     deg: 6 # degree of misspecification
#     scheduler: False # scheduler (boolean)
#     max_epochs: 30 # maximum number of epochs
#     min_epochs: 5 # minimum number of epochs
#     num_workers: 0 # maximum number of workers
#     batch_size: 128 # batch size
#     normalization: "zscore" # norm
#   smac:
#     walltime_limit: 86400
#     n_trials: 200
#     config_space_name: intopt_configspace
#     seed: 0

# - params:
#     name: ShortestPath
#     model: IMLE # name of the model
#     architecture_name: advanced
#     N: 1000 # dataset size
#     noise: 0.5 # noise halfwidth parameter
#     deg: 6 # degree of misspecification
#     scheduler: False # scheduler (boolean)
#     max_epochs: 30 # maximum number of epochs
#     min_epochs: 5 # minimum number of epochs
#     num_workers: 0 # maximum number of workers
#     batch_size: 128 # batch size
#     normalization: "zscore" # norm
#     nb_samples: 1 # number of samples parameter
#     nb_iterations: 1 # number of iterations

#   smac:
#     walltime_limit: 86400
#     n_trials: 200
#     config_space_name: imle_configspace
#     seed: 0

# - params:
#     name: ShortestPath
#     model: CachingPO # name of the model
#     loss: MAP_c # loss
#     architecture_name: advanced
#     N: 1000 # dataset size
#     noise: 0.5 # noise halfwidth parameter
#     deg: 6 # degree of misspecification
#     scheduler: False # scheduler (boolean)
#     max_epochs: 30 # maximum number of epochs
#     min_epochs: 5 # minimum number of epochs
#     num_workers: 0 # maximum number of workers
#     batch_size: 128 # batch size
#     normalization: "zscore" # norm
#     growth: 0.05 # growth parameter of rankwise losses
#     num_samples: 1
#   smac:
#     walltime_limit: 86400
#     n_trials: 200
#     config_space_name: caching_mapc_configspace
#     seed: 0

# - params:
#     name: ShortestPath
#     model: CachingPO # name of the model
#     loss: listwise # loss
#     architecture_name: advanced
#     N: 1000 # dataset size
#     noise: 0.5 # noise halfwidth parameter
#     deg: 6 # degree of misspecification
#     scheduler: False # scheduler (boolean)
#     max_epochs: 30 # maximum number of epochs
#     min_epochs: 5 # minimum number of epochs
#     num_workers: 0 # maximum number of workers
#     batch_size: 128 # batch size
#     normalization: "zscore" # norm
#     growth: 0.05 # growth parameter of rankwise losses
#     num_samples: 1
#   smac:
#     walltime_limit: 86400
#     n_trials: 200
#     config_space_name: caching_listwise_configspace
#     seed: 0









