- name: Knapsack
  model: baseline_mse
  architecture_name: advanced
  capacity: 120 # capacity of knapsack
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  scheduler: False # scheduler (boolean)
  lr: 0.5015609846941
  max_epochs: 35 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: "zscore" # norm

- name: Knapsack
  capacity: 120 # capacity of knapsack
  model: IntOpt # name of the model
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  thr: 1.7232516073536
  damping: 0.0009775142243
  scheduler: False # scheduler (boolean)
  lr: 0.9665661850483
  max_epochs: 35 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: "zscore" # norm

- name: Knapsack
  capacity: 120 # capacity of knapsack
  model: DCOL # name of the model
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  mu: 0.3878192935443
  scheduler: False # scheduler (boolean)
  lr: 0.0290687103727 
  max_epochs: 35 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: "zscore" # norm

- name: Knapsack
  capacity: 120 # capacity of knapsack
  model: SPO # name of the model
  architecture_name: advanced
  seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] # seed
  scheduler: False # scheduler (boolean)
  lr: 0.1357406124648 # learning rate
  max_epochs: 35 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: "zscore" # norm

- name: Knapsack
  capacity: 120 # capacity of knapsack
  model: DBB # name of the model
  architecture_name: advanced
  seed: [0,1,2,3,4,5, 6,7,8,9] # seed
  lambda_val: 0.3451093034103 # interpolation parameter blackbox
  scheduler: False # scheduler (boolean)
  lr: 0.1402067172943 # learning rate
  max_epochs: 35 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: "zscore" # norm

- name: Knapsack
  capacity: 120 # capacity of knapsack
  model: FenchelYoung # name of the model
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  sigma: 1.0838358575217
  num_samples: 1 # number of samples FY
  scheduler: False # scheduler (boolean)
  lr: 0.1777360705928
  max_epochs: 35 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: "zscore" # norm

- name: Knapsack
  capacity: 120 # capacity of knapsack
  model: IMLE # name of the model
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  temperature: 0.1829215644195
  nb_iterations: 1 # number of iterations
  k: 43
  nb_samples: 1 # number of samples parameter
  beta: 3.5372286067452
  scheduler: False # scheduler (boolean)
  lr: 0.4132986385067
  max_epochs: 35 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: "zscore" # norm
  
- name: Knapsack
  capacity: 120
  model: CachingPO
  loss: MAP_c
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  lr: 0.3730196026651 
  growth: 0.05 # growth parameter of rankwise losses
  max_epochs: 35 #35
  min_epochs: 5
  num_workers: 0 # maximum number of workers
  batch_size: 128
  normalization: "zscore"

- name: Knapsack
  capacity: 120
  model: CachingPO
  loss: pairwise
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  growth: 0.05 # growth parameter of rankwise losses
  max_epochs: 35 #35
  min_epochs: 5
  num_workers: 0 # maximum number of workers
  batch_size: 128
  normalization: "zscore"
  lr: 0.0710957039774
  tau: 0.0340290552048

- name: Knapsack
  capacity: 120
  model: CachingPO
  loss: pairwise_diff
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  lr: 0.2671237993127
  growth: 0.05 # growth parameter of rankwise losses
  max_epochs: 35 #35
  min_epochs: 5
  num_workers: 0 # maximum number of workers
  batch_size: 128
  normalization: "zscore"

- name: Knapsack
  capacity: 120
  model: CachingPO
  loss: listwise 
  architecture_name: advanced
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  lr: 0.0047864278566
  tau: 0.2770962457823
  growth: 0.05 # growth parameter of rankwise losses
  max_epochs: 35 #35
  min_epochs: 5
  num_workers: 0 # maximum number of workers
  batch_size: 128
  normalization: zscore