- name: ShortestPath
  model: baseline  # name of the model
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [1,2,3,4,5,6,7,8,9] # seed
  scheduler: False # scheduler (boolean)
  lr: 1.0 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: listwise # loss
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  tau: 1.0 # parameter of rankwise losses
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 0.1 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: pairwise # loss
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  tau: 10.0 # parameter of rankwise losses
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 1.0 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: pairwise_diff # loss
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 0.1 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: MAP_c # loss
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [6,7,8,9] # seed
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 1 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model: DBB  # name of the model
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  lambda_val: 0.1 # interpolation parameter blackbox
  scheduler: False # scheduler (boolean)
  lr: 0.05 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model:  DCOL # name of the model
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  mu: 10.0 # regularization parameter DCOL & QPTL
  scheduler: False # scheduler (boolean)
  lr: 0.1 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization
  regularizer: quadratic # regularizer 

- name: ShortestPath
  model: FenchelYoung  # name of the model
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  sigma: 0.1 # DPO FY noise parameter
  num_samples: 1 # number of samples FY
  scheduler: False # scheduler (boolean)
  lr: 0.05 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model: IMLE # name of the model
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  temperature: 0.5 # input and target noise temperature parameter
  nb_iterations: 1 # number of iterations
  k: 5 # parameter k
  nb_samples: 1 # number of samples parameter
  beta: 10.0 # parameter lambda of IMLE
  scheduler: False # scheduler (boolean)
  lr: 0.5 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization

- name: ShortestPath
  model: IntOpt  # name of the model
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  lambda_val: 1.0 # interpolation parameter blackbox
  thr: 0.001 # threshold parameter
  damping: 0.000001 # damping parameter
  scheduler: False # scheduler (boolean)
  lr: 0.1 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization
  regularizer: quadratic # regularizer 
  diffKKT: False # Whether KKT or HSD

- name: ShortestPath
  model: SPO # name of the model
  architecture_name: standard
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  scheduler: False # scheduler (boolean)
  lr: 1.0 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.00001 # weight of l1 regularization