- name: ShortestPath
  model: baseline  # name of the model
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  scheduler: False # scheduler (boolean)
  lr: 0.1688448512755 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0329558080818 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: listwise # loss
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  tau:  0.2544193371231 # parameter of rankwise losses
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 0.0068315974506 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0000011271744 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: pairwise # loss
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  tau: 3.904477591409 # parameter of rankwise losses
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 0.0024690751552 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0000002403947 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: pairwise_diff # loss
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 0.1935282337323 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0108547656904 # weight of l1 regularization

- name: ShortestPath
  model: CachingPO # name of the model
  loss: MAP_c # loss
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  growth: 0.05 # growth parameter of rankwise losses
  scheduler: False # scheduler (boolean)
  lr: 0.0666459079619 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0000096302766 # weight of l1 regularization

- name: ShortestPath
  model: DBB  # name of the model
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  lambda_val: 10.6875366825295 # interpolation parameter blackbox
  scheduler: False # scheduler (boolean)
  lr: 0.001479618314 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0011134350618 # weight of l1 regularization

- name: ShortestPath
  model:  DCOL # name of the model
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  mu: 2.9570506647422 # regularization parameter DCOL & QPTL
  scheduler: False # scheduler (boolean)
  lr: 0.0027280318118 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0003283721303 # weight of l1 regularization
  regularizer: quadratic # regularizer 

- name: ShortestPath
  model: FenchelYoung  # name of the model
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  sigma: 0.1614097641333 # DPO FY noise parameter
  num_samples: 1 # number of samples FY
  scheduler: False # scheduler (boolean)
  lr: 0.0021008248235 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0006159391649 # weight of l1 regularization

- name: ShortestPath
  model: IMLE # name of the model
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0, 1,2,3,4,5,6,7,8,9] # seed
  temperature: 1.0661000838612 # input and target noise temperature parameter
  nb_iterations: 1 # number of iterations
  k: 19 # parameter k
  nb_samples: 1 # number of samples parameter
  beta: 39.8633222830147 # parameter lambda of IMLE
  scheduler: False # scheduler (boolean)
  lr: 0.0010405800127 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0000200475943 # weight of l1 regularization

- name: ShortestPath
  model: IntOpt  # name of the model
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  lambda_val: 1.0 # interpolation parameter blackbox
  thr: 0.4133417155204 # threshold parameter
  damping: 0.0000010236124 # damping parameter
  scheduler: False # scheduler (boolean)
  lr: 0.0018371953706 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.001213628686 # weight of l1 regularization
  regularizer: quadratic # regularizer 
  diffKKT: False # Whether KKT or HSD

- name: ShortestPath
  model: SPO # name of the model
  architecture_name: advanced
  N: 1000 # dataset size
  noise: 0.5 # noise halfwidth parameter
  deg: 6 # degree of misspecification
  seed: [0,1,2,3,4,5,6,7,8,9] # seed
  scheduler: False # scheduler (boolean)
  lr: 0.0237835787724 # learning rate
  max_epochs: 30 # maximum number of epochs
  min_epochs: 5 # minimum number of epochs
  num_workers: 0 # maximum number of workers
  batch_size: 128 # batch size
  normalization: zscore # norm
  l1_weight: 0.0025642363624 # weight of l1 regularization